[S98.MO004] atualizacao-dados-escopo
AppCivico/smae pull request #105
Opened 2024-12-19 20:05 UTC by GustavoFSoares

[Task ID](https://trello.com/c/qU3xIy5d/1679-s98mo004-atualizacao-dos-dados-do-escopo)

2025-01-13 15:05 UTC, robsonsobral approved these changes

2025-01-14 19:41 UTC, robsonsobral requested changes

2025-01-14 19:41 UTC, robsonsobral commented on frontend/src/views/mdo.obras/ObraResumo.vue
> +          <div>{{ grupoPortfolio.sigla }}</div>
Para que essa `div`?

2025-01-14 19:41 UTC, robsonsobral commented on frontend/src/_less/_base.less
> +    margin-bottom: 2px;
Evitar unidades de medida absoluta para essas coisas conserva os cabelos, @GustavoFSoares .

2025-01-14 19:41 UTC, Eduruiz commented on frontend/src/views/mdo.obras/ObraResumo.vue
> +          {{ emFoco?.mdo_previsao_inauguracao ?
acho que seguindo o nosso linter esse `?` deveria estar na linha abaixo.

2025-01-14 19:41 UTC, Eduruiz commented on frontend/src/views/mdo.obras/ObraResumo.vue
> +            emFoco?.tarefa_cronograma?.previsao_custo ?
mesma coisa aqui :)

2025-01-15 12:45 UTC, robsonsobral approved these changes

2025-01-15 14:52 UTC, merged